---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always
      
jobs:
  macos-x86_64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true

      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
          use-cross: true

      - name: Optimize and package binary
        run: |
          cd target/release
          strip check_commit_for_issue
          chmod +x check_commit_for_issue
          mkdir dmg
          mv check_commit_for_issue dmg/
          hdiutil create -fs HFS+ -srcfolder dmg -volname check_commit_for_issue check_commit_for_issue.dmg
      
      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: target/release/check_commit_for_issue.dmg 
           
